"""MQTT Device Discovery payload for DigitalHouses Speedtest."""

from __future__ import annotations

from typing import Any

DEVICE_ID = "digitalhouses_global_speedtest"
DEVICE_NAME = "Internet Speedtest"

# Existing 1.0.0 identity contract. These values must never change.
LEGACY_COMPONENT_IDENTITIES: dict[str, tuple[str, str]] = {
    "download": ("digitalhouses_global_speedtest_download", "sensor.internet_speed_download"),
    "upload": ("digitalhouses_global_speedtest_upload", "sensor.internet_speed_upload"),
    "ping": ("digitalhouses_global_speedtest_ping", "sensor.internet_speed_ping"),
    "jitter": ("digitalhouses_global_speedtest_jitter", "sensor.internet_speed_jitter"),
    "packet_loss": (
        "digitalhouses_global_speedtest_packet_loss",
        "sensor.internet_speed_packet_loss",
    ),
    "status": ("digitalhouses_global_speedtest_status", "sensor.internet_speed_status"),
    "server": ("digitalhouses_global_speedtest_server", "sensor.internet_speed_server"),
    "server_id": (
        "digitalhouses_global_speedtest_server_id",
        "sensor.internet_speed_server_id",
    ),
    "provider": (
        "digitalhouses_global_speedtest_provider",
        "sensor.internet_speed_provider",
    ),
    "external_ip": (
        "digitalhouses_global_speedtest_external_ip",
        "sensor.internet_speed_external_ip",
    ),
    "last_test": (
        "digitalhouses_global_speedtest_last_test",
        "sensor.internet_speed_last_test",
    ),
    "result_url": (
        "digitalhouses_global_speedtest_result_url",
        "sensor.internet_speed_result_url",
    ),
    "run_test": ("digitalhouses_global_speedtest_run", "button.internet_speed_run"),
    "google_dns": (
        "digitalhouses_global_speedtest_google_dns_connectivity",
        "binary_sensor.internet_google_dns_connectivity",
    ),
    "cloudflare_dns": (
        "digitalhouses_global_speedtest_cloudflare_dns_connectivity",
        "binary_sensor.internet_cloudflare_dns_connectivity",
    ),
    "available_servers": (
        "digitalhouses_global_speedtest_available_servers",
        "sensor.internet_speed_available_servers",
    ),
    "server_list_updated": (
        "digitalhouses_global_speedtest_server_list_updated",
        "sensor.internet_speed_server_list_updated",
    ),
    "refresh_servers": (
        "digitalhouses_global_speedtest_refresh_servers",
        "button.internet_speed_refresh_servers",
    ),
}


def _availability(topic: str) -> dict[str, str]:
    return {
        "topic": topic,
        "payload_available": "online",
        "payload_not_available": "offline",
    }


def build_discovery_payload(
    *,
    app_version: str,
    expire_after_seconds: int,
    topics: dict[str, str],
) -> dict[str, Any]:
    """Build one Home Assistant MQTT Device Discovery document."""
    app_availability = [_availability(topics["app_availability"])]
    result_availability = [
        _availability(topics["app_availability"]),
        _availability(topics["result_availability"]),
    ]
    measurement_expiry = (
        {"expire_after": expire_after_seconds} if expire_after_seconds else {}
    )

    device = {
        "identifiers": [DEVICE_ID],
        "name": DEVICE_NAME,
        "manufacturer": "DigitalHouses",
        "model": "Official Ookla Speedtest CLI",
        "sw_version": app_version,
    }

    components: dict[str, Any] = {
        "download": {
            "platform": "sensor",
            "name": "Download",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["download"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["download"][1],
            "state_topic": topics["state"],
            "device_class": "data_rate",
            "state_class": "measurement",
            "unit_of_measurement": "Mbit/s",
            "suggested_display_precision": 1,
            "value_template": "{{ value_json.download_mbps }}",
            "icon": "mdi:download-network",
            "availability": result_availability,
            "availability_mode": "all",
            **measurement_expiry,
        },
        "upload": {
            "platform": "sensor",
            "name": "Upload",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["upload"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["upload"][1],
            "state_topic": topics["state"],
            "device_class": "data_rate",
            "state_class": "measurement",
            "unit_of_measurement": "Mbit/s",
            "suggested_display_precision": 1,
            "value_template": "{{ value_json.upload_mbps }}",
            "icon": "mdi:upload-network",
            "availability": result_availability,
            "availability_mode": "all",
            **measurement_expiry,
        },
        "ping": {
            "platform": "sensor",
            "name": "Ping",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["ping"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["ping"][1],
            "state_topic": topics["state"],
            "device_class": "duration",
            "state_class": "measurement",
            "unit_of_measurement": "ms",
            "suggested_display_precision": 1,
            "value_template": "{{ value_json.ping_ms }}",
            "icon": "mdi:timer-outline",
            "availability": result_availability,
            "availability_mode": "all",
            **measurement_expiry,
        },
        "jitter": {
            "platform": "sensor",
            "name": "Jitter",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["jitter"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["jitter"][1],
            "state_topic": topics["state"],
            "device_class": "duration",
            "state_class": "measurement",
            "unit_of_measurement": "ms",
            "suggested_display_precision": 1,
            "value_template": "{{ value_json.jitter_ms }}",
            "entity_category": "diagnostic",
            "availability": result_availability,
            "availability_mode": "all",
            **measurement_expiry,
        },
        "packet_loss": {
            "platform": "sensor",
            "name": "Packet loss",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["packet_loss"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["packet_loss"][1],
            "state_topic": topics["state"],
            "state_class": "measurement",
            "unit_of_measurement": "%",
            "suggested_display_precision": 1,
            "value_template": "{{ value_json.packet_loss }}",
            "entity_category": "diagnostic",
            "icon": "mdi:package-variant-remove",
            "availability": result_availability,
            "availability_mode": "all",
            **measurement_expiry,
        },
        "status": {
            "platform": "sensor",
            "name": "Status",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["status"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["status"][1],
            "state_topic": topics["state"],
            "device_class": "enum",
            "options": ["Ready", "Running", "Success", "Error", "No connectivity"],
            "value_template": "{{ value_json.status }}",
            "json_attributes_topic": topics["state"],
            "json_attributes_template": (
                "{{ {'last_attempt': value_json.last_attempt, "
                "'error': value_json.error} | tojson }}"
            ),
            "icon": "mdi:speedometer",
            "availability": app_availability,
        },
        "server": {
            "platform": "sensor",
            "name": "Server",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["server"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["server"][1],
            "state_topic": topics["state"],
            "value_template": "{{ value_json.server }}",
            "entity_category": "diagnostic",
            "icon": "mdi:server-network",
            "availability": app_availability,
        },
        "server_id": {
            "platform": "sensor",
            "name": "Server ID",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["server_id"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["server_id"][1],
            "state_topic": topics["state"],
            "value_template": "{{ value_json.server_id }}",
            "entity_category": "diagnostic",
            "icon": "mdi:identifier",
            "availability": app_availability,
        },
        "provider": {
            "platform": "sensor",
            "name": "Provider",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["provider"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["provider"][1],
            "state_topic": topics["state"],
            "value_template": "{{ value_json.provider }}",
            "entity_category": "diagnostic",
            "icon": "mdi:wan",
            "availability": app_availability,
        },
        "external_ip": {
            "platform": "sensor",
            "name": "External IP",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["external_ip"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["external_ip"][1],
            "state_topic": topics["state"],
            "value_template": "{{ value_json.external_ip }}",
            "entity_category": "diagnostic",
            "icon": "mdi:ip-network",
            "availability": app_availability,
        },
        "last_test": {
            "platform": "sensor",
            "name": "Last successful test",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["last_test"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["last_test"][1],
            "state_topic": topics["state"],
            "device_class": "timestamp",
            "value_template": "{{ value_json.last_success }}",
            "entity_category": "diagnostic",
            "icon": "mdi:clock-check-outline",
            "availability": app_availability,
        },
        "result_url": {
            "platform": "sensor",
            "name": "Ookla result URL",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["result_url"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["result_url"][1],
            "state_topic": topics["state"],
            "value_template": "{{ value_json.result_url }}",
            "entity_category": "diagnostic",
            "icon": "mdi:open-in-new",
            "availability": app_availability,
        },
        "run_test": {
            "platform": "button",
            "name": "Run speed test",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["run_test"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["run_test"][1],
            "command_topic": topics["command"],
            "payload_press": "RUN",
            "entity_category": "config",
            "icon": "mdi:play-speed",
            "availability": app_availability,
        },
        "google_dns": {
            "platform": "binary_sensor",
            "name": "Google DNS connectivity",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["google_dns"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["google_dns"][1],
            "device_class": "connectivity",
            "state_topic": topics["connectivity"],
            "value_template": "{{ 'ON' if value_json.google_dns else 'OFF' }}",
            "payload_on": "ON",
            "payload_off": "OFF",
            "entity_category": "diagnostic",
            "availability": app_availability,
        },
        "cloudflare_dns": {
            "platform": "binary_sensor",
            "name": "Cloudflare DNS connectivity",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["cloudflare_dns"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["cloudflare_dns"][1],
            "device_class": "connectivity",
            "state_topic": topics["connectivity"],
            "value_template": "{{ 'ON' if value_json.cloudflare_dns else 'OFF' }}",
            "payload_on": "ON",
            "payload_off": "OFF",
            "entity_category": "diagnostic",
            "availability": app_availability,
        },
        "available_servers": {
            "platform": "sensor",
            "name": "Available Speedtest servers",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["available_servers"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["available_servers"][1],
            "state_topic": topics["servers"],
            "value_template": "{{ value_json.count }}",
            "unit_of_measurement": "servers",
            "json_attributes_topic": topics["servers"],
            "json_attributes_template": (
                "{{ {'updated_at': value_json.updated_at, "
                "'servers': value_json.servers, "
                "'error': value_json.error} | tojson }}"
            ),
            "entity_category": "diagnostic",
            "icon": "mdi:server-plus",
            "availability": app_availability,
        },
        "server_list_updated": {
            "platform": "sensor",
            "name": "Server list updated",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["server_list_updated"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["server_list_updated"][1],
            "state_topic": topics["servers"],
            "device_class": "timestamp",
            "value_template": "{{ value_json.updated_at or '' }}",
            "entity_category": "diagnostic",
            "icon": "mdi:clock-refresh-outline",
            "availability": app_availability,
        },
        "refresh_servers": {
            "platform": "button",
            "name": "Refresh server list",
            "unique_id": LEGACY_COMPONENT_IDENTITIES["refresh_servers"][0],
            "default_entity_id": LEGACY_COMPONENT_IDENTITIES["refresh_servers"][1],
            "command_topic": topics["command"],
            "payload_press": "REFRESH_SERVERS",
            "entity_category": "config",
            "icon": "mdi:refresh",
            "availability": app_availability,
        },
        "minimum_download": {
            "platform": "number",
            "name": "Minimum download speed",
            "unique_id": f"{DEVICE_ID}_minimum_download",
            "default_entity_id": "number.internet_speed_minimum_download",
            "state_topic": topics["thresholds"],
            "value_template": "{{ value_json.minimum_download_mbps }}",
            "command_topic": topics["minimum_download_command"],
            "unit_of_measurement": "Mbit/s",
            "min": 1,
            "max": 10000,
            "step": 1,
            "mode": "box",
            "icon": "mdi:download-network-outline",
            "entity_category": "config",
            "availability": app_availability,
        },
        "minimum_upload": {
            "platform": "number",
            "name": "Minimum upload speed",
            "unique_id": f"{DEVICE_ID}_minimum_upload",
            "default_entity_id": "number.internet_speed_minimum_upload",
            "state_topic": topics["thresholds"],
            "value_template": "{{ value_json.minimum_upload_mbps }}",
            "command_topic": topics["minimum_upload_command"],
            "unit_of_measurement": "Mbit/s",
            "min": 1,
            "max": 10000,
            "step": 1,
            "mode": "box",
            "icon": "mdi:upload-network-outline",
            "entity_category": "config",
            "availability": app_availability,
        },
        "maximum_ping": {
            "platform": "number",
            "name": "Maximum ping",
            "unique_id": f"{DEVICE_ID}_maximum_ping",
            "default_entity_id": "number.internet_speed_maximum_ping",
            "state_topic": topics["thresholds"],
            "value_template": "{{ value_json.maximum_ping_ms }}",
            "command_topic": topics["maximum_ping_command"],
            "unit_of_measurement": "ms",
            "min": 1,
            "max": 1000,
            "step": 1,
            "mode": "box",
            "icon": "mdi:timer-alert-outline",
            "entity_category": "config",
            "availability": app_availability,
        },
        "periodic_interval": {
            "platform": "number",
            "name": "Periodic test interval",
            "unique_id": f"{DEVICE_ID}_periodic_interval",
            "default_entity_id": "number.internet_speed_periodic_interval",
            "state_topic": topics["schedule"],
            "value_template": (
                "{{ value_json.periodic_test_interval_minutes }}"
            ),
            "command_topic": topics["periodic_interval_command"],
            "unit_of_measurement": "min",
            "min": 5,
            "max": 720,
            "step": 5,
            "mode": "box",
            "icon": "mdi:timer-cog-outline",
            "entity_category": "config",
            "availability": app_availability,
        },
        "low_download": {
            "platform": "binary_sensor",
            "name": "Low download speed",
            "unique_id": f"{DEVICE_ID}_low_download",
            "default_entity_id": "binary_sensor.internet_speed_low_download",
            "device_class": "problem",
            "state_topic": topics["problems"],
            "value_template": "{{ value_json.low_download.state }}",
            "payload_on": "ON",
            "payload_off": "OFF",
            "json_attributes_topic": topics["problems"],
            "json_attributes_template": (
                "{{ value_json.low_download.attributes | tojson }}"
            ),
            "icon": "mdi:download-network-outline",
            "availability": result_availability,
            "availability_mode": "all",
        },
        "low_upload": {
            "platform": "binary_sensor",
            "name": "Low upload speed",
            "unique_id": f"{DEVICE_ID}_low_upload",
            "default_entity_id": "binary_sensor.internet_speed_low_upload",
            "device_class": "problem",
            "state_topic": topics["problems"],
            "value_template": "{{ value_json.low_upload.state }}",
            "payload_on": "ON",
            "payload_off": "OFF",
            "json_attributes_topic": topics["problems"],
            "json_attributes_template": "{{ value_json.low_upload.attributes | tojson }}",
            "icon": "mdi:upload-network-outline",
            "availability": result_availability,
            "availability_mode": "all",
        },
        "high_ping": {
            "platform": "binary_sensor",
            "name": "High ping",
            "unique_id": f"{DEVICE_ID}_high_ping",
            "default_entity_id": "binary_sensor.internet_speed_high_ping",
            "device_class": "problem",
            "state_topic": topics["problems"],
            "value_template": "{{ value_json.high_ping.state }}",
            "payload_on": "ON",
            "payload_off": "OFF",
            "json_attributes_topic": topics["problems"],
            "json_attributes_template": "{{ value_json.high_ping.attributes | tojson }}",
            "icon": "mdi:timer-alert-outline",
            "availability": result_availability,
            "availability_mode": "all",
        },
        "performance_problem": {
            "platform": "binary_sensor",
            "name": "Internet performance problem",
            "unique_id": f"{DEVICE_ID}_performance_problem",
            "default_entity_id": "binary_sensor.internet_speed_performance_problem",
            "device_class": "problem",
            "state_topic": topics["problems"],
            "value_template": "{{ value_json.performance_problem.state }}",
            "payload_on": "ON",
            "payload_off": "OFF",
            "json_attributes_topic": topics["problems"],
            "json_attributes_template": (
                "{{ value_json.performance_problem.attributes | tojson }}"
            ),
            "icon": "mdi:alert-circle-outline",
            "availability": result_availability,
            "availability_mode": "all",
        },
        "recent_results": {
            "platform": "sensor",
            "name": "Recent results",
            "unique_id": f"{DEVICE_ID}_recent_results",
            "default_entity_id": "sensor.internet_speed_recent_results",
            "state_topic": topics["recent_results"],
            "value_template": "{{ value_json.count }}",
            "unit_of_measurement": "tests",
            "json_attributes_topic": topics["recent_results"],
            "json_attributes_template": (
                "{{ {'updated_at': value_json.updated_at, "
                "'count': value_json.count, "
                "'limit': value_json.limit, "
                "'results': value_json.results} | tojson }}"
            ),
            "entity_category": "diagnostic",
            "icon": "mdi:history",
            "availability": app_availability,
        },
    }

    return {
        "device": device,
        "origin": {
            "name": "DigitalHouses Speedtest App",
            "sw_version": app_version,
        },
        "components": components,
    }
